# SPDX-License-Identifier: Apache-2.0
"""Evidence audit: what justifies each element in the register?

A closed vocabulary is only defensible if every element in it earns its place.
"It seemed useful" is how a finite vocabulary stops being finite. This asks a
harder question of each of the 53 elements:

    has any *real* document, from a corpus nobody curated for this purpose,
    actually needed it?

Three verdicts:

  CORPUS    exercised by real documents in at least one corpus. Earned.
  FIXTURE   exercised only by the conformance document, which the author
            wrote. That is an assertion, not evidence.
  UNTESTED  not exercised anywhere. Should not exist yet.

L2 and L3 can never be evidenced by a corpus of published static documents --
there are no forms in a gazette. They are marked as needing a different kind of
validation rather than being counted as failures.

    python3 tools/evidence.py            # table + verdict
    python3 tools/evidence.py --write     # also write spec/EVIDENCE.md
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import stoa  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CORPORA = [("Diavgeia", ROOT / "corpus" / "RESULTS.md"),
           ("RFCs", ROOT / "corpus" / "RESULTS-rfc.md"),
           ("JATS", ROOT / "corpus" / "RESULTS-jats.md")]


def used_in(path):
    if not path.exists():
        return set()
    s = path.read_text(encoding="utf-8")
    return set(re.findall(r"^\| `([a-z-]+)` \| L\d", s, re.M))


def used_in_fixture(reg):
    doc = stoa.load_document(ROOT / "conformance" / "conformance-01.json")
    return {stoa.typ(n) for n, _ in stoa.walk(doc) if stoa.typ(n) in reg}


def audit():
    reg = stoa.Register()
    seen = {name: used_in(p) for name, p in CORPORA}
    fixture = used_in_fixture(reg)
    union = set().union(*seen.values()) if seen else set()

    rows = []
    for e in reg.raw["elements"]:
        n, layer = e["n"], e["layer"]
        where = [k for k, v in seen.items() if n in v]
        if where:
            verdict = "CORPUS"
        elif n in fixture:
            verdict = "FIXTURE" if layer < 2 else "BY DESIGN"
        else:
            verdict = "UNTESTED"
        rows.append((n, layer, verdict, ", ".join(where) or "—"))
    return reg, rows, union, fixture


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()

    reg, rows, union, fixture = audit()
    total = len(reg.elements)
    corpus_backed = sum(1 for r in rows if r[2] == "CORPUS")
    fixture_only = [r for r in rows if r[2] == "FIXTURE"]
    by_design = [r for r in rows if r[2] == "BY DESIGN"]
    untested = [r for r in rows if r[2] == "UNTESTED"]

    out = []
    w = out.append
    w("<!-- generated by tools/evidence.py; do not edit -->")
    w("# Evidence audit\n")
    w("What justifies each element in the register. A closed vocabulary is only "
      "defensible if every element earns its place, so this asks whether a real "
      "document -- from a corpus nobody curated for the purpose -- actually "
      "needed it.\n")
    w(f"| Verdict | Count | Meaning |")
    w(f"|---|---|---|")
    w(f"| **CORPUS** | {corpus_backed} of {total} | Exercised by real documents. Earned. |")
    w(f"| **BY DESIGN** | {len(by_design)} of {total} | L2/L3. A corpus of published static documents cannot contain a form or a typed renderer payload; these need an authored conformance target instead, and have one. |")
    w(f"| **FIXTURE** | {len(fixture_only)} of {total} | L0/L1, exercised only by the document the author wrote. An assertion, not evidence. |")
    w(f"| **UNTESTED** | {len(untested)} of {total} | Not exercised anywhere. |")
    w("")

    if not [r for r in rows if r[1] == 0 and r[2] != "CORPUS"]:
        w("## Every L0 element is backed by real documents\n")
        w("L0 is the layer that freezes permanently, so it is the layer where "
          "an unearned element is unfixable. Every one of them is now "
          "exercised by a document nobody wrote for this project.\n")
    if fixture_only:
        w("## Elements resting on assertion\n")
        w("These are L0 or L1 and no real document in either corpus used them.\n")
        w("Read this as a statement about the corpora, not automatically about "
          "the elements. Neither genre chosen so far contains a footnote or an "
          "image: the first is JSON metadata wrapped around a PDF, and RFCs are "
          "text-only by tradition and cite rather than footnote. That is a "
          "corpus artifact, and it is exactly why the verdict is *unproven* "
          "rather than *unnecessary*.\n")
        w("It is still a gap, and it is precise about what would close it: a "
          "third genre containing footnotes and figures. Legislation with "
          "footnoted recitals, or scholarly articles in JATS, would settle all "
          "three L0 entries at once. Until then these elements rest on the "
          "author's judgement, and after the freeze that judgement is "
          "permanent.\n")
        for n, layer, _, _ in fixture_only:
            note = reg[n].get("note", "")
            w(f"- **`{n}`** (L{layer}) — {note[:160] if note else 'no rationale recorded'}")
        w("")
    if untested:
        w("## Elements with no evidence at all\n")
        for n, layer, _, _ in untested:
            w(f"- **`{n}`** (L{layer})")
        w("")

    w("## Full table\n")
    w("| Element | Layer | Verdict | Seen in |")
    w("|---|---|---|---|")
    for n, layer, verdict, where in rows:
        w(f"| `{n}` | L{layer} | {verdict} | {where} |")
    w("")
    w(f"Union across both corpora: **{len(union)} of {total}** elements "
      f"exercised by real documents.\n")

    text = "\n".join(out)
    print(text)
    if a.write:
        (ROOT / "spec" / "EVIDENCE.md").write_text(text + "\n", encoding="utf-8")
        print(f"\n[written to spec/EVIDENCE.md]", file=sys.stderr)

    # An L0 element with no corpus evidence is the thing that must not survive
    # the freeze unnoticed, so make it a non-zero exit rather than a paragraph.
    l0_unproven = [r for r in rows if r[1] == 0 and r[2] in ("FIXTURE", "UNTESTED")]
    if l0_unproven:
        print(f"\n{len(l0_unproven)} L0 elements rest on assertion: "
              f"{', '.join(r[0] for r in l0_unproven)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
